# Dockerfile.rag
FROM python:3.11-slim

WORKDIR /rag

COPY ./rag /rag
COPY requirements-rag.txt /rag/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py", "--index"]
